In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

sns.set(style = 'whitegrid')

In [ ]:
df = pd.read_csv('world_cup_1975.csv')
df

,Id,Date,Countries,Ground,Result
0,1,07/06/1975,England v. India,Lord's,England won by 202 runs
1,2,07/06/1975,East Africa v. New Zealand,Edgbaston,New Zealand won by 181 runs
2,3,07/06/1975,Australia v. Pakistan,Headingley,Australia won by 73 runs
3,4,07/06/1975,Sri Lanka v. West Indies,Old Trafford,West Indies won by 9 wickets
4,5,11/06/1975,England v. New Zealand,Trent Bridge,England won by 80 runs
5,6,11/06/1975,East Africa v. India,Headingley,India won by 10 wickets
6,7,11/06/1975,Australia v. Sri Lanka,Kennington Oval,Australia won by 52 runs
7,8,11/06/1975,Pakistan v. West Indies,Edgbaston,West Indies won by 1 wicket
8,9,14/06/1975,England v. East Africa,Edgbaston,England won by 196 runs
9,10,14/06/1975,India v. New Zealand,Old Trafford,New Zealand won by 4 wickets
10,11,14/06/1975,Australia v. West Indies,Kennington Oval,West Indies won by 7 wickets
11,12,14/06/1975,Pakistan v. Sri Lanka,Trent Bridge,Pakistan won by 192 runs
12,13,18/06/1975,England v. Australia,Headingley,Australia won by 4 wickets
13,14,18/06/1975,New Zealand v. West Indies,Kennington Oval,West Indies won by 5 wickets
14,15,21/06/1975,Australia v. West Indies,Lord's,West Indies won by 17 runs

In [ ]:
# 1. Total number of matches played in the dataset.

total_matches = int(df['Countries'].count().sum())
# total_matches
print(f'The total number of matches played: {total_matches}')
# df.shape

The total number of matches played: 15

In [24]:
# 2. Which team has the highest win percentage?

winners = {}
total_matches = len(df['Result'])

for i in df['Result']:
  name = i.split('won')[0].strip() # Added strip() to remove leading/trailing spaces
  winners[name] = winners.get(name, 0) + 1

win_percentages = {}
for team, wins in winners.items():

    perc = (wins / total_matches) * 100
    win_percentages[team] = perc

highest_win_team = max(win_percentages, key=win_percentages.get)
highest_win_percentage_value = win_percentages[highest_win_team]


for team, perc in win_percentages.items():
    print(f"{team} : {perc:.2f}%")

print(f"\n{highest_win_team} : {highest_win_percentage_value:.2f}%.")

England : 20.00%
New Zealand : 13.33%
Australia : 20.00%
West Indies : 33.33%
India : 6.67%
Pakistan : 6.67%

West Indies : 33.33%.

In [27]:
# 6. Which stadium hosted the most matches?

df['Ground'].value_counts().sort_values(ascending=False).head(1)

Ground
Edgbaston    3
Name: count, dtype: int64

In [ ]:
# 🔍 EDA Questions to Answer:

# 1. Total number of matches played in the dataset.


# 2. Which team has the highest win percentage?


# 3. Top 5 batsmen by total runs scored.


# 4. Top 5 bowlers by total wickets taken.


# 5. Average runs scored per match.


# 6. Which stadium hosted the most matches?


# 7. How many matches ended without a result?


# 8. Highest team total in the dataset.


# 9. Total boundaries (4s and 6s) hit in the tournament.


# 10. Visualize runs scored trend by match number.

# 📌 Task Requirements:

# Perform data cleaning if required.

# Use Pandas for manipulation and Matplotlib / Seaborn for visualization